hostname: localhost
port: 8000

context_servers:
  num_instances: 1
  router:
    type: round_robin
  urls:
    - "localhost:8001"

generation_servers:
  num_instances: 1
  urls:
    - "localhost:8002"
