hostname: 0.0.0.0
port: 8000

context_servers:
  num_instances: 1
  router:
    type: round_robin
  urls:
    - "127.0.0.1:8001"

generation_servers:
  num_instances: 1
  urls:
    - "127.0.0.1:8002"
